// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: guru/cex/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Request type for the Query/ModeratorAddress RPC method.
type QueryModeratorAddressRequest struct {
}

func (m *QueryModeratorAddressRequest) Reset()         { *m = QueryModeratorAddressRequest{} }
func (m *QueryModeratorAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryModeratorAddressRequest) ProtoMessage()    {}
func (*QueryModeratorAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{0}
}
func (m *QueryModeratorAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryModeratorAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryModeratorAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryModeratorAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModeratorAddressRequest.Merge(m, src)
}
func (m *QueryModeratorAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryModeratorAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModeratorAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModeratorAddressRequest proto.InternalMessageInfo

// Response type for the Query/ModeratorAddress RPC method.
type QueryModeratorAddressResponse struct {
	ModeratorAddress string `protobuf:"bytes,1,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
}

func (m *QueryModeratorAddressResponse) Reset()         { *m = QueryModeratorAddressResponse{} }
func (m *QueryModeratorAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryModeratorAddressResponse) ProtoMessage()    {}
func (*QueryModeratorAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{1}
}
func (m *QueryModeratorAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryModeratorAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryModeratorAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryModeratorAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModeratorAddressResponse.Merge(m, src)
}
func (m *QueryModeratorAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryModeratorAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModeratorAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModeratorAddressResponse proto.InternalMessageInfo

func (m *QueryModeratorAddressResponse) GetModeratorAddress() string {
	if m != nil {
		return m.ModeratorAddress
	}
	return ""
}

// Request type for the Query/Coin RPC method.
type QueryAttributesRequest struct {
	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *QueryAttributesRequest) Reset()         { *m = QueryAttributesRequest{} }
func (m *QueryAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAttributesRequest) ProtoMessage()    {}
func (*QueryAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{2}
}
func (m *QueryAttributesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttributesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttributesRequest.Merge(m, src)
}
func (m *QueryAttributesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttributesRequest proto.InternalMessageInfo

func (m *QueryAttributesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryAttributesRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Response type for the Query/Coin RPC method.
type QueryAttributesResponse struct {
	Attributes []Attribute `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes"`
}

func (m *QueryAttributesResponse) Reset()         { *m = QueryAttributesResponse{} }
func (m *QueryAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAttributesResponse) ProtoMessage()    {}
func (*QueryAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{3}
}
func (m *QueryAttributesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttributesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttributesResponse.Merge(m, src)
}
func (m *QueryAttributesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttributesResponse proto.InternalMessageInfo

func (m *QueryAttributesResponse) GetAttributes() []Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// Request type for the Query/CoinPair RPC method.
type QueryExchangesRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryExchangesRequest) Reset()         { *m = QueryExchangesRequest{} }
func (m *QueryExchangesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryExchangesRequest) ProtoMessage()    {}
func (*QueryExchangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{4}
}
func (m *QueryExchangesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryExchangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryExchangesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryExchangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryExchangesRequest.Merge(m, src)
}
func (m *QueryExchangesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryExchangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryExchangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryExchangesRequest proto.InternalMessageInfo

func (m *QueryExchangesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response type for the Query/CoinPair RPC method.
type QueryExchangesResponse struct {
	Exchanges []Exchange `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges"`
}

func (m *QueryExchangesResponse) Reset()         { *m = QueryExchangesResponse{} }
func (m *QueryExchangesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryExchangesResponse) ProtoMessage()    {}
func (*QueryExchangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{5}
}
func (m *QueryExchangesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryExchangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryExchangesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryExchangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryExchangesResponse.Merge(m, src)
}
func (m *QueryExchangesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryExchangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryExchangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryExchangesResponse proto.InternalMessageInfo

func (m *QueryExchangesResponse) GetExchanges() []Exchange {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

// Request type for the Query/CoinPair RPC method.
type QueryIsAdminRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryIsAdminRequest) Reset()         { *m = QueryIsAdminRequest{} }
func (m *QueryIsAdminRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsAdminRequest) ProtoMessage()    {}
func (*QueryIsAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{6}
}
func (m *QueryIsAdminRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsAdminRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsAdminRequest.Merge(m, src)
}
func (m *QueryIsAdminRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsAdminRequest proto.InternalMessageInfo

func (m *QueryIsAdminRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Response type for the Query/CoinPair RPC method.
type QueryIsAdminResponse struct {
	IsAdmin bool `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
}

func (m *QueryIsAdminResponse) Reset()         { *m = QueryIsAdminResponse{} }
func (m *QueryIsAdminResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIsAdminResponse) ProtoMessage()    {}
func (*QueryIsAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{7}
}
func (m *QueryIsAdminResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsAdminResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsAdminResponse.Merge(m, src)
}
func (m *QueryIsAdminResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsAdminResponse proto.InternalMessageInfo

func (m *QueryIsAdminResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

// Request type for the Query/CoinPair RPC method.
type QueryNextExchangeIdRequest struct {
}

func (m *QueryNextExchangeIdRequest) Reset()         { *m = QueryNextExchangeIdRequest{} }
func (m *QueryNextExchangeIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNextExchangeIdRequest) ProtoMessage()    {}
func (*QueryNextExchangeIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{8}
}
func (m *QueryNextExchangeIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNextExchangeIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNextExchangeIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNextExchangeIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNextExchangeIdRequest.Merge(m, src)
}
func (m *QueryNextExchangeIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNextExchangeIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNextExchangeIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNextExchangeIdRequest proto.InternalMessageInfo

// Response type for the Query/CoinPair RPC method.
type QueryNextExchangeIdResponse struct {
	Id github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=id,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"id"`
}

func (m *QueryNextExchangeIdResponse) Reset()         { *m = QueryNextExchangeIdResponse{} }
func (m *QueryNextExchangeIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNextExchangeIdResponse) ProtoMessage()    {}
func (*QueryNextExchangeIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{9}
}
func (m *QueryNextExchangeIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNextExchangeIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNextExchangeIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNextExchangeIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNextExchangeIdResponse.Merge(m, src)
}
func (m *QueryNextExchangeIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNextExchangeIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNextExchangeIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNextExchangeIdResponse proto.InternalMessageInfo

// Request type for the Query/Coin RPC method.
type QueryRatemeterRequest struct {
}

func (m *QueryRatemeterRequest) Reset()         { *m = QueryRatemeterRequest{} }
func (m *QueryRatemeterRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRatemeterRequest) ProtoMessage()    {}
func (*QueryRatemeterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{10}
}
func (m *QueryRatemeterRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRatemeterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRatemeterRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRatemeterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRatemeterRequest.Merge(m, src)
}
func (m *QueryRatemeterRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRatemeterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRatemeterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRatemeterRequest proto.InternalMessageInfo

// Response type for the Query/Coin RPC method.
type QueryRatemeterResponse struct {
	Ratemeter Ratemeter `protobuf:"bytes,1,opt,name=ratemeter,proto3" json:"ratemeter"`
}

func (m *QueryRatemeterResponse) Reset()         { *m = QueryRatemeterResponse{} }
func (m *QueryRatemeterResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRatemeterResponse) ProtoMessage()    {}
func (*QueryRatemeterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03253bdc2f527e22, []int{11}
}
func (m *QueryRatemeterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRatemeterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRatemeterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRatemeterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRatemeterResponse.Merge(m, src)
}
func (m *QueryRatemeterResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRatemeterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRatemeterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRatemeterResponse proto.InternalMessageInfo

func (m *QueryRatemeterResponse) GetRatemeter() Ratemeter {
	if m != nil {
		return m.Ratemeter
	}
	return Ratemeter{}
}

func init() {
	proto.RegisterType((*QueryModeratorAddressRequest)(nil), "guru.cex.v1.QueryModeratorAddressRequest")
	proto.RegisterType((*QueryModeratorAddressResponse)(nil), "guru.cex.v1.QueryModeratorAddressResponse")
	proto.RegisterType((*QueryAttributesRequest)(nil), "guru.cex.v1.QueryAttributesRequest")
	proto.RegisterType((*QueryAttributesResponse)(nil), "guru.cex.v1.QueryAttributesResponse")
	proto.RegisterType((*QueryExchangesRequest)(nil), "guru.cex.v1.QueryExchangesRequest")
	proto.RegisterType((*QueryExchangesResponse)(nil), "guru.cex.v1.QueryExchangesResponse")
	proto.RegisterType((*QueryIsAdminRequest)(nil), "guru.cex.v1.QueryIsAdminRequest")
	proto.RegisterType((*QueryIsAdminResponse)(nil), "guru.cex.v1.QueryIsAdminResponse")
	proto.RegisterType((*QueryNextExchangeIdRequest)(nil), "guru.cex.v1.QueryNextExchangeIdRequest")
	proto.RegisterType((*QueryNextExchangeIdResponse)(nil), "guru.cex.v1.QueryNextExchangeIdResponse")
	proto.RegisterType((*QueryRatemeterRequest)(nil), "guru.cex.v1.QueryRatemeterRequest")
	proto.RegisterType((*QueryRatemeterResponse)(nil), "guru.cex.v1.QueryRatemeterResponse")
}

func init() { proto.RegisterFile("guru/cex/v1/query.proto", fileDescriptor_03253bdc2f527e22) }

var fileDescriptor_03253bdc2f527e22 = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0x8d, 0xc3, 0xf7, 0x01, 0xb9, 0x48, 0x88, 0x4e, 0xf9, 0x09, 0x2e, 0x98, 0x60, 0x5a, 0x7e,
	0x5a, 0xe1, 0x51, 0xe8, 0xaa, 0x88, 0x4d, 0x90, 0xaa, 0x2a, 0x12, 0xad, 0xda, 0x14, 0xa9, 0x52,
	0x37, 0x91, 0x13, 0x8f, 0xcc, 0x28, 0xc4, 0x13, 0xec, 0x49, 0xe4, 0x08, 0xb1, 0x61, 0xd9, 0x55,
	0x51, 0x5f, 0xa5, 0x0f, 0xc1, 0x12, 0xb5, 0x9b, 0xaa, 0x0b, 0x54, 0x41, 0x1f, 0xa4, 0xf2, 0x78,
	0x6c, 0xec, 0x38, 0xa4, 0x5d, 0x61, 0xdf, 0x7b, 0xee, 0xb9, 0x47, 0xc7, 0xf7, 0x10, 0x58, 0xb0,
	0xbb, 0x6e, 0x17, 0x37, 0x89, 0x8f, 0x7b, 0x65, 0x7c, 0xd2, 0x25, 0x6e, 0xdf, 0xe8, 0xb8, 0x8c,
	0x33, 0x34, 0x15, 0x34, 0x8c, 0x26, 0xf1, 0x8d, 0x5e, 0x59, 0x9d, 0x4b, 0xa2, 0x82, 0x9a, 0xc0,
	0xa8, 0x5a, 0x93, 0x79, 0x6d, 0xe6, 0xe1, 0x86, 0xe9, 0x11, 0xdc, 0x2b, 0x37, 0x08, 0x37, 0xcb,
	0xb8, 0xc9, 0xa8, 0x23, 0xfb, 0x8b, 0x61, 0xbf, 0x2e, 0xde, 0x70, 0xf8, 0x22, 0x5b, 0xb3, 0x36,
	0xb3, 0x59, 0x58, 0x0f, 0x9e, 0x64, 0x75, 0xc9, 0x66, 0xcc, 0x3e, 0x26, 0xd8, 0xec, 0x50, 0x6c,
	0x3a, 0x0e, 0xe3, 0x26, 0xa7, 0xcc, 0x91, 0x33, 0xba, 0x06, 0x4b, 0xef, 0x02, 0x85, 0xaf, 0x99,
	0x45, 0x5c, 0x93, 0x33, 0xb7, 0x62, 0x59, 0x2e, 0xf1, 0xbc, 0x1a, 0x39, 0xe9, 0x12, 0x8f, 0xeb,
	0x07, 0xb0, 0x7c, 0x4f, 0xdf, 0xeb, 0x30, 0xc7, 0x23, 0xe8, 0x19, 0x3c, 0x68, 0x47, 0xbd, 0xba,
	0x19, 0x36, 0x8b, 0x4a, 0x49, 0xd9, 0x2c, 0xd4, 0x66, 0xda, 0x03, 0x43, 0xfa, 0x2e, 0xcc, 0x0b,
	0xb6, 0x0a, 0xe7, 0x2e, 0x6d, 0x74, 0x39, 0x89, 0xf6, 0xa0, 0x69, 0xc8, 0x53, 0x4b, 0xce, 0xe5,
	0xa9, 0x85, 0x66, 0x60, 0xac, 0x45, 0xfa, 0xc5, 0xbc, 0x28, 0x04, 0x8f, 0xfa, 0x07, 0x58, 0xc8,
	0xcc, 0x4a, 0x0d, 0x7b, 0x00, 0x66, 0x5c, 0x2d, 0x2a, 0xa5, 0xb1, 0xcd, 0xa9, 0x9d, 0x79, 0x23,
	0x61, 0xb6, 0x11, 0x0f, 0xed, 0xff, 0x77, 0x79, 0xbd, 0x92, 0xab, 0x25, 0xf0, 0xfa, 0x06, 0xcc,
	0x09, 0xe2, 0x97, 0x7e, 0xf3, 0xc8, 0x74, 0xec, 0x7b, 0x35, 0xe9, 0xef, 0xa5, 0xfa, 0x04, 0x50,
	0x0a, 0x78, 0x01, 0x05, 0x12, 0x15, 0xe5, 0xfe, 0xb9, 0xd4, 0xfe, 0x68, 0x44, 0xae, 0xbf, 0x43,
	0xeb, 0x18, 0x1e, 0x0a, 0xd2, 0xaa, 0x57, 0xb1, 0xda, 0xd4, 0x89, 0x76, 0x17, 0x61, 0x22, 0x6d,
	0x66, 0xf4, 0xaa, 0x97, 0x61, 0x36, 0x3d, 0x20, 0x35, 0x2c, 0xc2, 0x24, 0xf5, 0xea, 0x66, 0x50,
	0x13, 0x23, 0x93, 0xb5, 0x09, 0x1a, 0x42, 0xf4, 0x25, 0x50, 0xc5, 0xc8, 0x1b, 0xe2, 0xf3, 0x48,
	0x49, 0xd5, 0x8a, 0x3e, 0x71, 0x0b, 0x1e, 0x0d, 0xed, 0x4a, 0xde, 0x83, 0x3b, 0x17, 0xf6, 0xf7,
	0x02, 0xf5, 0x3f, 0xaf, 0x57, 0xd6, 0x6d, 0xca, 0x8f, 0xba, 0x0d, 0xa3, 0xc9, 0xda, 0xf2, 0x04,
	0xe5, 0x9f, 0x6d, 0xcf, 0x6a, 0x61, 0xde, 0xef, 0x10, 0xcf, 0xa8, 0x3a, 0xfc, 0xdb, 0xd7, 0x6d,
	0x90, 0x17, 0x5a, 0x75, 0xb8, 0xf0, 0x70, 0x41, 0x9a, 0x5d, 0x33, 0x39, 0x69, 0x13, 0x4e, 0xdc,
	0x48, 0xc5, 0xa1, 0x34, 0x37, 0xd1, 0x90, 0x02, 0x76, 0xa1, 0xe0, 0x46, 0x45, 0xa1, 0x63, 0xf0,
	0xe3, 0xc6, 0x23, 0x91, 0xbb, 0x31, 0x7c, 0xe7, 0x62, 0x1c, 0xfe, 0x17, 0xb4, 0xe8, 0x42, 0x81,
	0x99, 0xc1, 0x23, 0x46, 0x5b, 0x29, 0x9e, 0x51, 0x41, 0x50, 0x9f, 0xfe, 0x0b, 0x34, 0x54, 0xac,
	0xaf, 0x9f, 0x7f, 0xff, 0xfd, 0x25, 0x5f, 0x42, 0x1a, 0x4e, 0x66, 0x3c, 0x13, 0x13, 0x74, 0xae,
	0x00, 0xdc, 0x9d, 0x33, 0x5a, 0xcb, 0xae, 0xc8, 0x04, 0x45, 0x7d, 0x3c, 0x1a, 0x24, 0x15, 0x6c,
	0x09, 0x05, 0x6b, 0x68, 0x35, 0xa5, 0x20, 0xf8, 0x37, 0x52, 0xef, 0x98, 0xd4, 0xc5, 0xa7, 0xd4,
	0x3a, 0xc3, 0xa7, 0x2d, 0xd2, 0x3f, 0x43, 0x1c, 0x0a, 0xf1, 0x41, 0x23, 0x3d, 0xcb, 0x3e, 0x18,
	0x0b, 0x75, 0x6d, 0x24, 0x46, 0x0a, 0xd0, 0x84, 0x80, 0x22, 0x9a, 0x4f, 0x09, 0x88, 0xcf, 0x1e,
	0xf5, 0x60, 0x42, 0x1e, 0x30, 0x2a, 0x65, 0xf9, 0xd2, 0x61, 0x50, 0x57, 0x47, 0x20, 0x46, 0x5a,
	0x4e, 0x3d, 0x91, 0x07, 0x7c, 0x2a, 0x1d, 0x3f, 0x43, 0x9f, 0x14, 0x98, 0x4e, 0x1f, 0x3a, 0xda,
	0xc8, 0xb2, 0x0f, 0x0d, 0x8a, 0xba, 0xf9, 0x77, 0xa0, 0x54, 0xf3, 0x44, 0xa8, 0x59, 0x41, 0xcb,
	0x29, 0x35, 0x0e, 0xf1, 0x79, 0x3d, 0xb2, 0xa0, 0x4e, 0xad, 0xc0, 0xfa, 0xf8, 0x76, 0x87, 0x59,
	0x3f, 0x18, 0x92, 0x61, 0xd6, 0x67, 0xf2, 0x72, 0x8f, 0xf5, 0x71, 0x26, 0xf6, 0x2b, 0x97, 0x37,
	0x9a, 0x72, 0x75, 0xa3, 0x29, 0xbf, 0x6e, 0x34, 0xe5, 0xf3, 0xad, 0x96, 0xbb, 0xba, 0xd5, 0x72,
	0x3f, 0x6e, 0xb5, 0xdc, 0xc7, 0x8d, 0x44, 0xac, 0x5f, 0xbd, 0x3d, 0xf4, 0xb7, 0xed, 0x63, 0xd6,
	0x30, 0x8f, 0x43, 0x1e, 0x5f, 0x30, 0x89, 0x6c, 0x37, 0xc6, 0xc5, 0x8f, 0xc7, 0xf3, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xac, 0x06, 0xff, 0xdf, 0xea, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ModeratorAddress returns the current moderator address
	ModeratorAddress(ctx context.Context, in *QueryModeratorAddressRequest, opts ...grpc.CallOption) (*QueryModeratorAddressResponse, error)
	Attributes(ctx context.Context, in *QueryAttributesRequest, opts ...grpc.CallOption) (*QueryAttributesResponse, error)
	Exchanges(ctx context.Context, in *QueryExchangesRequest, opts ...grpc.CallOption) (*QueryExchangesResponse, error)
	IsAdmin(ctx context.Context, in *QueryIsAdminRequest, opts ...grpc.CallOption) (*QueryIsAdminResponse, error)
	NextExchangeId(ctx context.Context, in *QueryNextExchangeIdRequest, opts ...grpc.CallOption) (*QueryNextExchangeIdResponse, error)
	Ratemeter(ctx context.Context, in *QueryRatemeterRequest, opts ...grpc.CallOption) (*QueryRatemeterResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ModeratorAddress(ctx context.Context, in *QueryModeratorAddressRequest, opts ...grpc.CallOption) (*QueryModeratorAddressResponse, error) {
	out := new(QueryModeratorAddressResponse)
	err := c.cc.Invoke(ctx, "/guru.cex.v1.Query/ModeratorAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Attributes(ctx context.Context, in *QueryAttributesRequest, opts ...grpc.CallOption) (*QueryAttributesResponse, error) {
	out := new(QueryAttributesResponse)
	err := c.cc.Invoke(ctx, "/guru.cex.v1.Query/Attributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Exchanges(ctx context.Context, in *QueryExchangesRequest, opts ...grpc.CallOption) (*QueryExchangesResponse, error) {
	out := new(QueryExchangesResponse)
	err := c.cc.Invoke(ctx, "/guru.cex.v1.Query/Exchanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IsAdmin(ctx context.Context, in *QueryIsAdminRequest, opts ...grpc.CallOption) (*QueryIsAdminResponse, error) {
	out := new(QueryIsAdminResponse)
	err := c.cc.Invoke(ctx, "/guru.cex.v1.Query/IsAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NextExchangeId(ctx context.Context, in *QueryNextExchangeIdRequest, opts ...grpc.CallOption) (*QueryNextExchangeIdResponse, error) {
	out := new(QueryNextExchangeIdResponse)
	err := c.cc.Invoke(ctx, "/guru.cex.v1.Query/NextExchangeId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Ratemeter(ctx context.Context, in *QueryRatemeterRequest, opts ...grpc.CallOption) (*QueryRatemeterResponse, error) {
	out := new(QueryRatemeterResponse)
	err := c.cc.Invoke(ctx, "/guru.cex.v1.Query/Ratemeter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ModeratorAddress returns the current moderator address
	ModeratorAddress(context.Context, *QueryModeratorAddressRequest) (*QueryModeratorAddressResponse, error)
	Attributes(context.Context, *QueryAttributesRequest) (*QueryAttributesResponse, error)
	Exchanges(context.Context, *QueryExchangesRequest) (*QueryExchangesResponse, error)
	IsAdmin(context.Context, *QueryIsAdminRequest) (*QueryIsAdminResponse, error)
	NextExchangeId(context.Context, *QueryNextExchangeIdRequest) (*QueryNextExchangeIdResponse, error)
	Ratemeter(context.Context, *QueryRatemeterRequest) (*QueryRatemeterResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ModeratorAddress(ctx context.Context, req *QueryModeratorAddressRequest) (*QueryModeratorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModeratorAddress not implemented")
}
func (*UnimplementedQueryServer) Attributes(ctx context.Context, req *QueryAttributesRequest) (*QueryAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attributes not implemented")
}
func (*UnimplementedQueryServer) Exchanges(ctx context.Context, req *QueryExchangesRequest) (*QueryExchangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exchanges not implemented")
}
func (*UnimplementedQueryServer) IsAdmin(ctx context.Context, req *QueryIsAdminRequest) (*QueryIsAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAdmin not implemented")
}
func (*UnimplementedQueryServer) NextExchangeId(ctx context.Context, req *QueryNextExchangeIdRequest) (*QueryNextExchangeIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextExchangeId not implemented")
}
func (*UnimplementedQueryServer) Ratemeter(ctx context.Context, req *QueryRatemeterRequest) (*QueryRatemeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ratemeter not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ModeratorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryModeratorAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ModeratorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.cex.v1.Query/ModeratorAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ModeratorAddress(ctx, req.(*QueryModeratorAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Attributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Attributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.cex.v1.Query/Attributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Attributes(ctx, req.(*QueryAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Exchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Exchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.cex.v1.Query/Exchanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Exchanges(ctx, req.(*QueryExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IsAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIsAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IsAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.cex.v1.Query/IsAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IsAdmin(ctx, req.(*QueryIsAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NextExchangeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNextExchangeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NextExchangeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.cex.v1.Query/NextExchangeId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NextExchangeId(ctx, req.(*QueryNextExchangeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Ratemeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRatemeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Ratemeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.cex.v1.Query/Ratemeter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Ratemeter(ctx, req.(*QueryRatemeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guru.cex.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModeratorAddress",
			Handler:    _Query_ModeratorAddress_Handler,
		},
		{
			MethodName: "Attributes",
			Handler:    _Query_Attributes_Handler,
		},
		{
			MethodName: "Exchanges",
			Handler:    _Query_Exchanges_Handler,
		},
		{
			MethodName: "IsAdmin",
			Handler:    _Query_IsAdmin_Handler,
		},
		{
			MethodName: "NextExchangeId",
			Handler:    _Query_NextExchangeId_Handler,
		},
		{
			MethodName: "Ratemeter",
			Handler:    _Query_Ratemeter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guru/cex/v1/query.proto",
}

func (m *QueryModeratorAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryModeratorAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryModeratorAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryModeratorAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryModeratorAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryModeratorAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAttributesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttributesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttributesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAttributesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttributesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttributesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attributes) > 0 {
		for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryExchangesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryExchangesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryExchangesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryExchangesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryExchangesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryExchangesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Exchanges) > 0 {
		for iNdEx := len(m.Exchanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Exchanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryIsAdminRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsAdminRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsAdminRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIsAdminResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsAdminResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsAdminResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsAdmin {
		i--
		if m.IsAdmin {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryNextExchangeIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNextExchangeIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNextExchangeIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryNextExchangeIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNextExchangeIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNextExchangeIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Id.Size()
		i -= size
		if _, err := m.Id.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRatemeterRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRatemeterRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRatemeterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRatemeterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRatemeterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRatemeterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Ratemeter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryModeratorAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryModeratorAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAttributesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAttributesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Attributes) > 0 {
		for _, e := range m.Attributes {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryExchangesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryExchangesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Exchanges) > 0 {
		for _, e := range m.Exchanges {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryIsAdminRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIsAdminResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsAdmin {
		n += 2
	}
	return n
}

func (m *QueryNextExchangeIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryNextExchangeIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Id.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRatemeterRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRatemeterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Ratemeter.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryModeratorAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryModeratorAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryModeratorAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryModeratorAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryModeratorAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryModeratorAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttributesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttributesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttributesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttributesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttributesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttributesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, Attribute{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryExchangesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryExchangesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryExchangesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryExchangesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryExchangesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryExchangesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exchanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Exchanges = append(m.Exchanges, Exchange{})
			if err := m.Exchanges[len(m.Exchanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsAdminRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsAdminRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsAdminRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsAdminResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsAdminResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsAdminResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsAdmin", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsAdmin = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNextExchangeIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNextExchangeIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNextExchangeIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNextExchangeIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNextExchangeIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNextExchangeIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRatemeterRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRatemeterRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRatemeterRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRatemeterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRatemeterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRatemeterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ratemeter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Ratemeter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
