// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: guru/oracle/v1/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the oracle module's genesis state
type GenesisState struct {
	// params defines all the parameters of the module
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// request_oracle_docs defines the list of oracle request documents
	RequestOracleDocs []RequestOracleDoc `protobuf:"bytes,2,rep,name=request_oracle_docs,json=requestOracleDocs,proto3" json:"request_oracle_docs"`
	// moderator_address defines the address of the oracle moderator
	ModeratorAddress string `protobuf:"bytes,3,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4a1ce927fa70879, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetRequestOracleDocs() []RequestOracleDoc {
	if m != nil {
		return m.RequestOracleDocs
	}
	return nil
}

func (m *GenesisState) GetModeratorAddress() string {
	if m != nil {
		return m.ModeratorAddress
	}
	return ""
}

// Params defines the parameters for the oracle module
type Params struct {
	// enable_oracle defines whether the oracle module is enabled
	EnableOracle bool `protobuf:"varint,1,opt,name=enable_oracle,json=enableOracle,proto3" json:"enable_oracle,omitempty"`
	// submit_window defines the time window in seconds for submitting oracle data
	SubmitWindow uint64 `protobuf:"varint,2,opt,name=submit_window,json=submitWindow,proto3" json:"submit_window,omitempty"`
	// min_submit_per_window defines the minimum number of submissions required per window
	MinSubmitPerWindow github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=min_submit_per_window,json=minSubmitPerWindow,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"min_submit_per_window"`
	// slash_fraction_downtime defines the fraction of stake to slash for downtime
	SlashFractionDowntime github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=slash_fraction_downtime,json=slashFractionDowntime,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"slash_fraction_downtime"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4a1ce927fa70879, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEnableOracle() bool {
	if m != nil {
		return m.EnableOracle
	}
	return false
}

func (m *Params) GetSubmitWindow() uint64 {
	if m != nil {
		return m.SubmitWindow
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "guru.oracle.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "guru.oracle.v1.Params")
}

func init() { proto.RegisterFile("guru/oracle/v1/genesis.proto", fileDescriptor_c4a1ce927fa70879) }

var fileDescriptor_c4a1ce927fa70879 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xd1, 0x6a, 0xd4, 0x40,
	0x18, 0x85, 0x77, 0xb6, 0xcb, 0xa2, 0xd3, 0x28, 0x36, 0x5a, 0x0d, 0x55, 0xd2, 0x50, 0x41, 0x82,
	0xd2, 0x09, 0xad, 0xbe, 0x80, 0x4b, 0xb0, 0x97, 0x2e, 0xa9, 0x28, 0x78, 0x13, 0x26, 0xc9, 0x34,
	0x1d, 0xcc, 0xe4, 0x8f, 0x33, 0x93, 0x6e, 0x7d, 0x0b, 0x5f, 0xc0, 0xf7, 0xa9, 0x77, 0xbd, 0x14,
	0x2f, 0x8a, 0xec, 0xbe, 0x88, 0x64, 0x66, 0x56, 0x74, 0x2f, 0xbd, 0x4a, 0x38, 0xe7, 0xf0, 0x9d,
	0x33, 0xf0, 0xe3, 0x27, 0x75, 0x2f, 0xfb, 0x04, 0x24, 0x2d, 0x1b, 0x96, 0x5c, 0x1c, 0x25, 0x35,
	0x6b, 0x99, 0xe2, 0x8a, 0x74, 0x12, 0x34, 0xf8, 0x77, 0x07, 0x97, 0x58, 0x97, 0x5c, 0x1c, 0xed,
	0x3d, 0xa8, 0xa1, 0x06, 0x63, 0x25, 0xc3, 0x9f, 0x4d, 0xed, 0x3d, 0xde, 0x60, 0xb8, 0xbc, 0x31,
	0x0f, 0xbe, 0x23, 0xec, 0x9d, 0x58, 0xe8, 0xa9, 0xa6, 0x9a, 0xf9, 0xaf, 0xf0, 0xb4, 0xa3, 0x92,
	0x0a, 0x15, 0xa0, 0x08, 0xc5, 0xdb, 0xc7, 0x0f, 0xc9, 0xbf, 0x25, 0x64, 0x6e, 0xdc, 0xd9, 0xe4,
	0xea, 0x66, 0x7f, 0x94, 0xb9, 0xac, 0xff, 0x1e, 0xdf, 0x97, 0xec, 0x73, 0xcf, 0x94, 0xce, 0x6d,
	0x32, 0xaf, 0xa0, 0x54, 0xc1, 0x38, 0xda, 0x8a, 0xb7, 0x8f, 0xa3, 0x4d, 0x44, 0x66, 0xa3, 0x6f,
	0x8d, 0x90, 0x42, 0xe9, 0x60, 0x3b, 0x72, 0x43, 0x57, 0xfe, 0x0b, 0xbc, 0x23, 0xa0, 0x62, 0x92,
	0x6a, 0x90, 0x39, 0xad, 0x2a, 0xc9, 0x94, 0x0a, 0xb6, 0x22, 0x14, 0xdf, 0xce, 0xee, 0xfd, 0x31,
	0x5e, 0x5b, 0xfd, 0xe0, 0xdb, 0x18, 0x4f, 0xed, 0x3a, 0xff, 0x29, 0xbe, 0xc3, 0x5a, 0x5a, 0x34,
	0xcc, 0xcd, 0x31, 0x8f, 0xb9, 0x95, 0x79, 0x56, 0xb4, 0x05, 0x43, 0x48, 0xf5, 0x85, 0xe0, 0x3a,
	0x5f, 0xf0, 0xb6, 0x82, 0x45, 0x30, 0x8e, 0x50, 0x3c, 0xc9, 0x3c, 0x2b, 0x7e, 0x30, 0x9a, 0x4f,
	0xf1, 0xae, 0xe0, 0x6d, 0xee, 0x82, 0x1d, 0x93, 0xeb, 0xf0, 0xb0, 0xc2, 0x9b, 0x91, 0x61, 0xf9,
	0xcf, 0x9b, 0xfd, 0x67, 0x35, 0xd7, 0xe7, 0x7d, 0x41, 0x4a, 0x10, 0x49, 0x09, 0x4a, 0x80, 0x72,
	0x9f, 0x43, 0x55, 0x7d, 0x4a, 0xf4, 0x97, 0x8e, 0x29, 0x92, 0xb2, 0x32, 0xf3, 0x05, 0x6f, 0x4f,
	0x0d, 0x6b, 0xce, 0xa4, 0xab, 0x38, 0xc3, 0x8f, 0x54, 0x43, 0xd5, 0x79, 0x7e, 0x26, 0x69, 0xa9,
	0x39, 0xb4, 0x79, 0x05, 0x8b, 0x56, 0x73, 0xc1, 0x82, 0xc9, 0x7f, 0x95, 0xec, 0x1a, 0xdc, 0x1b,
	0x47, 0x4b, 0x1d, 0x6c, 0x96, 0x5e, 0x2d, 0x43, 0x74, 0xbd, 0x0c, 0xd1, 0xaf, 0x65, 0x88, 0xbe,
	0xae, 0xc2, 0xd1, 0xf5, 0x2a, 0x1c, 0xfd, 0x58, 0x85, 0xa3, 0x8f, 0xcf, 0xff, 0x02, 0x9f, 0xcc,
	0xdf, 0x5d, 0x1e, 0xd6, 0x0d, 0x14, 0xb4, 0x49, 0xcc, 0xe5, 0x5c, 0xae, 0x6f, 0xc7, 0x14, 0x14,
	0x53, 0x73, 0x38, 0x2f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x50, 0x43, 0x7e, 0x32, 0x9b, 0x02,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RequestOracleDocs) > 0 {
		for iNdEx := len(m.RequestOracleDocs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RequestOracleDocs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.SlashFractionDowntime.Size()
		i -= size
		if _, err := m.SlashFractionDowntime.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MinSubmitPerWindow.Size()
		i -= size
		if _, err := m.MinSubmitPerWindow.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.SubmitWindow != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SubmitWindow))
		i--
		dAtA[i] = 0x10
	}
	if m.EnableOracle {
		i--
		if m.EnableOracle {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.RequestOracleDocs) > 0 {
		for _, e := range m.RequestOracleDocs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EnableOracle {
		n += 2
	}
	if m.SubmitWindow != 0 {
		n += 1 + sovGenesis(uint64(m.SubmitWindow))
	}
	l = m.MinSubmitPerWindow.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.SlashFractionDowntime.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestOracleDocs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestOracleDocs = append(m.RequestOracleDocs, RequestOracleDoc{})
			if err := m.RequestOracleDocs[len(m.RequestOracleDocs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableOracle", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableOracle = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitWindow", wireType)
			}
			m.SubmitWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmitWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSubmitPerWindow", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinSubmitPerWindow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionDowntime", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFractionDowntime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
