// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: guru/oracle/v1/oracle.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OracleType defines the type of oracle data that can be requested and provided
// This enum helps categorize different kinds of oracle data sources and their purposes
type OracleType int32

const (
	// Default value, should not be used
	OracleType_ORACLE_TYPE_UNSPECIFIED OracleType = 0
	// Minimum gas price oracle for network fee estimation
	OracleType_ORACLE_TYPE_MIN_GAS_PRICE OracleType = 1
	// Currency exchange rates and forex data
	OracleType_ORACLE_TYPE_CURRENCY OracleType = 2
	// Stock market data and indices
	OracleType_ORACLE_TYPE_STOCK OracleType = 3
	// Cryptocurrency prices and market data
	OracleType_ORACLE_TYPE_CRYPTO OracleType = 4
)

var OracleType_name = map[int32]string{
	0: "ORACLE_TYPE_UNSPECIFIED",
	1: "ORACLE_TYPE_MIN_GAS_PRICE",
	2: "ORACLE_TYPE_CURRENCY",
	3: "ORACLE_TYPE_STOCK",
	4: "ORACLE_TYPE_CRYPTO",
}

var OracleType_value = map[string]int32{
	"ORACLE_TYPE_UNSPECIFIED":   0,
	"ORACLE_TYPE_MIN_GAS_PRICE": 1,
	"ORACLE_TYPE_CURRENCY":      2,
	"ORACLE_TYPE_STOCK":         3,
	"ORACLE_TYPE_CRYPTO":        4,
}

func (x OracleType) String() string {
	return proto.EnumName(OracleType_name, int32(x))
}

func (OracleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f372f15f6da5f250, []int{0}
}

// RequestStatus defines the current state of an oracle request
// This helps track the lifecycle of oracle data requests
type RequestStatus int32

const (
	// Default value, should not be used
	RequestStatus_REQUEST_STATUS_UNSPECIFIED RequestStatus = 0
	// Request is waiting to be processed
	RequestStatus_REQUEST_STATUS_PENDING RequestStatus = 1
	// Request was successfully processed and data is available
	RequestStatus_REQUEST_STATUS_SUCCESS RequestStatus = 2
	// Request failed to process or data is invalid
	RequestStatus_REQUEST_STATUS_FAILED RequestStatus = 3
	// Request was stopped or cancelled
	RequestStatus_REQUEST_STATUS_STOP RequestStatus = 4
)

var RequestStatus_name = map[int32]string{
	0: "REQUEST_STATUS_UNSPECIFIED",
	1: "REQUEST_STATUS_PENDING",
	2: "REQUEST_STATUS_SUCCESS",
	3: "REQUEST_STATUS_FAILED",
	4: "REQUEST_STATUS_STOP",
}

var RequestStatus_value = map[string]int32{
	"REQUEST_STATUS_UNSPECIFIED": 0,
	"REQUEST_STATUS_PENDING":     1,
	"REQUEST_STATUS_SUCCESS":     2,
	"REQUEST_STATUS_FAILED":      3,
	"REQUEST_STATUS_STOP":        4,
}

func (x RequestStatus) String() string {
	return proto.EnumName(RequestStatus_name, int32(x))
}

func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f372f15f6da5f250, []int{1}
}

// AggregationRule defines the enumeration for aggregating oracle data
// Specifies how multiple data points should be combined into a single value
type AggregationRule int32

const (
	// Default value, should not be used
	AggregationRule_AGGREGATION_RULE_UNSPECIFIED AggregationRule = 0
	// Use average value to aggregate the data
	AggregationRule_AGGREGATION_RULE_AVG AggregationRule = 1
	// Use minimum value to aggregate the data
	AggregationRule_AGGREGATION_RULE_MIN AggregationRule = 2
	// Use maximum value to aggregate the data
	AggregationRule_AGGREGATION_RULE_MAX AggregationRule = 3
)

var AggregationRule_name = map[int32]string{
	0: "AGGREGATION_RULE_UNSPECIFIED",
	1: "AGGREGATION_RULE_AVG",
	2: "AGGREGATION_RULE_MIN",
	3: "AGGREGATION_RULE_MAX",
}

var AggregationRule_value = map[string]int32{
	"AGGREGATION_RULE_UNSPECIFIED": 0,
	"AGGREGATION_RULE_AVG":         1,
	"AGGREGATION_RULE_MIN":         2,
	"AGGREGATION_RULE_MAX":         3,
}

func (x AggregationRule) String() string {
	return proto.EnumName(AggregationRule_name, int32(x))
}

func (AggregationRule) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f372f15f6da5f250, []int{2}
}

// OracleRequestDoc defines the structure for oracle request documents
// This is the main document that describes what oracle data is needed and how it should be processed
type OracleRequestDoc struct {
	// Unique identifier for the oracle request
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Type of oracle data being requested
	OracleType OracleType `protobuf:"varint,2,opt,name=oracle_type,json=oracleType,proto3,enum=guru.oracle.v1.OracleType" json:"oracle_type,omitempty"`
	// Human-readable name for the oracle request
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Detailed description of what data is needed and its purpose
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Time period in seconds between data updates
	Period uint32 `protobuf:"varint,5,opt,name=period,proto3" json:"period,omitempty"`
	// List of account addresses that are authorized to provide data
	AccountList []string `protobuf:"bytes,6,rep,name=account_list,json=accountList,proto3" json:"account_list,omitempty"`
	// Minimum number of oracle nodes required to validate the data
	Quorum uint32 `protobuf:"varint,7,opt,name=quorum,proto3" json:"quorum,omitempty"`
	// Source URLs where the data can be fetched
	Urls []string `protobuf:"bytes,8,rep,name=urls,proto3" json:"urls,omitempty"`
	// JSONPath or similar rule to parse the raw data
	ParseRule string `protobuf:"bytes,9,opt,name=parse_rule,json=parseRule,proto3" json:"parse_rule,omitempty"`
	// Rule for aggregating multiple data points (e.g., median, mean)
	AggregateRule AggregationRule `protobuf:"varint,10,opt,name=aggregate_rule,json=aggregateRule,proto3,enum=guru.oracle.v1.AggregationRule" json:"aggregate_rule,omitempty"`
	// Current status of the request
	Status RequestStatus `protobuf:"varint,11,opt,name=status,proto3,enum=guru.oracle.v1.RequestStatus" json:"status,omitempty"`
	// Address of the request creator
	Creator string `protobuf:"bytes,12,opt,name=creator,proto3" json:"creator,omitempty"`
	// Sequential number to ensure data freshness
	Nonce uint64 `protobuf:"varint,13,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *OracleRequestDoc) Reset()         { *m = OracleRequestDoc{} }
func (m *OracleRequestDoc) String() string { return proto.CompactTextString(m) }
func (*OracleRequestDoc) ProtoMessage()    {}
func (*OracleRequestDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_f372f15f6da5f250, []int{0}
}
func (m *OracleRequestDoc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleRequestDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleRequestDoc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleRequestDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleRequestDoc.Merge(m, src)
}
func (m *OracleRequestDoc) XXX_Size() int {
	return m.Size()
}
func (m *OracleRequestDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleRequestDoc.DiscardUnknown(m)
}

var xxx_messageInfo_OracleRequestDoc proto.InternalMessageInfo

func (m *OracleRequestDoc) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *OracleRequestDoc) GetOracleType() OracleType {
	if m != nil {
		return m.OracleType
	}
	return OracleType_ORACLE_TYPE_UNSPECIFIED
}

func (m *OracleRequestDoc) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OracleRequestDoc) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *OracleRequestDoc) GetPeriod() uint32 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *OracleRequestDoc) GetAccountList() []string {
	if m != nil {
		return m.AccountList
	}
	return nil
}

func (m *OracleRequestDoc) GetQuorum() uint32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *OracleRequestDoc) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *OracleRequestDoc) GetParseRule() string {
	if m != nil {
		return m.ParseRule
	}
	return ""
}

func (m *OracleRequestDoc) GetAggregateRule() AggregationRule {
	if m != nil {
		return m.AggregateRule
	}
	return AggregationRule_AGGREGATION_RULE_UNSPECIFIED
}

func (m *OracleRequestDoc) GetStatus() RequestStatus {
	if m != nil {
		return m.Status
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

func (m *OracleRequestDoc) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *OracleRequestDoc) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

// SubmitDataSet defines the structure for oracle data sets for submit
// This represents a single data point provided by an oracle node
type SubmitDataSet struct {
	// ID of the request this data set belongs to
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Sequential number to prevent replay attacks
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Raw data in string format (can be JSON, CSV, etc.)
	RawData string `protobuf:"bytes,3,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	// Address of the data provider
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	// Cryptographic signature of the data for verification
	Signature string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SubmitDataSet) Reset()         { *m = SubmitDataSet{} }
func (m *SubmitDataSet) String() string { return proto.CompactTextString(m) }
func (*SubmitDataSet) ProtoMessage()    {}
func (*SubmitDataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f372f15f6da5f250, []int{1}
}
func (m *SubmitDataSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitDataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitDataSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitDataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitDataSet.Merge(m, src)
}
func (m *SubmitDataSet) XXX_Size() int {
	return m.Size()
}
func (m *SubmitDataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitDataSet.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitDataSet proto.InternalMessageInfo

func (m *SubmitDataSet) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *SubmitDataSet) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *SubmitDataSet) GetRawData() string {
	if m != nil {
		return m.RawData
	}
	return ""
}

func (m *SubmitDataSet) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *SubmitDataSet) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

// DataSet defines the structure for oracle data sets
type DataSet struct {
	// ID of the request this data set belongs to
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Sequential number to prevent replay attacks
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Block height - represents the height of the block where the data was aggregated
	BlockHeight uint64 `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Raw data in string format (can be JSON, CSV, etc.)
	RawData string `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
}

func (m *DataSet) Reset()         { *m = DataSet{} }
func (m *DataSet) String() string { return proto.CompactTextString(m) }
func (*DataSet) ProtoMessage()    {}
func (*DataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f372f15f6da5f250, []int{2}
}
func (m *DataSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSet.Merge(m, src)
}
func (m *DataSet) XXX_Size() int {
	return m.Size()
}
func (m *DataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSet.DiscardUnknown(m)
}

var xxx_messageInfo_DataSet proto.InternalMessageInfo

func (m *DataSet) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *DataSet) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *DataSet) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *DataSet) GetRawData() string {
	if m != nil {
		return m.RawData
	}
	return ""
}

func init() {
	proto.RegisterEnum("guru.oracle.v1.OracleType", OracleType_name, OracleType_value)
	proto.RegisterEnum("guru.oracle.v1.RequestStatus", RequestStatus_name, RequestStatus_value)
	proto.RegisterEnum("guru.oracle.v1.AggregationRule", AggregationRule_name, AggregationRule_value)
	proto.RegisterType((*OracleRequestDoc)(nil), "guru.oracle.v1.OracleRequestDoc")
	proto.RegisterType((*SubmitDataSet)(nil), "guru.oracle.v1.SubmitDataSet")
	proto.RegisterType((*DataSet)(nil), "guru.oracle.v1.DataSet")
}

func init() { proto.RegisterFile("guru/oracle/v1/oracle.proto", fileDescriptor_f372f15f6da5f250) }

var fileDescriptor_f372f15f6da5f250 = []byte{
	// 764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xdb, 0x46,
	0x10, 0x35, 0x25, 0xc5, 0xb6, 0xc6, 0x96, 0xcb, 0x6e, 0x1d, 0x87, 0x56, 0x62, 0x46, 0xf1, 0xc9,
	0x30, 0x50, 0x11, 0x6e, 0xd1, 0x53, 0x4f, 0x2c, 0x45, 0xab, 0x44, 0x1d, 0x49, 0x5d, 0x52, 0x45,
	0xdd, 0x0b, 0xb1, 0xa4, 0xb6, 0x34, 0x51, 0x8a, 0xcb, 0x2c, 0x97, 0x4e, 0x02, 0xf4, 0xd2, 0x3f,
	0x68, 0x8f, 0x45, 0x7f, 0xa8, 0xc7, 0x1c, 0xdb, 0x5b, 0x61, 0xff, 0x48, 0xc1, 0x25, 0xa3, 0x48,
	0x4c, 0x80, 0x1e, 0x7a, 0x9b, 0x79, 0x6f, 0xde, 0xec, 0xdb, 0x9d, 0xc5, 0xc0, 0xe3, 0xa8, 0xe0,
	0x85, 0xc1, 0x38, 0x09, 0x13, 0x6a, 0xdc, 0x5e, 0xd4, 0xd1, 0x30, 0xe3, 0x4c, 0x30, 0x74, 0x50,
	0x92, 0xc3, 0x1a, 0xba, 0xbd, 0xe8, 0x1f, 0x46, 0x2c, 0x62, 0x92, 0x32, 0xca, 0xa8, 0xaa, 0xea,
	0x3f, 0x8d, 0x18, 0x8b, 0x12, 0x6a, 0xc8, 0x2c, 0x28, 0x7e, 0x34, 0x44, 0xbc, 0xa4, 0xb9, 0x20,
	0xcb, 0xac, 0x2e, 0xd0, 0x43, 0x96, 0x2f, 0x59, 0x6e, 0x04, 0x24, 0x2f, 0xcf, 0x08, 0xa8, 0x20,
	0x17, 0x46, 0xc8, 0xe2, 0xb4, 0xe2, 0x4f, 0xff, 0x6e, 0x83, 0x3a, 0x95, 0x87, 0x60, 0xfa, 0xa2,
	0xa0, 0xb9, 0x18, 0xb1, 0x10, 0x9d, 0x00, 0xf0, 0x2a, 0xf3, 0xe3, 0x85, 0xa6, 0x0c, 0x94, 0xb3,
	0x0e, 0xee, 0xd6, 0x88, 0xb3, 0x40, 0x5f, 0xc2, 0x5e, 0xe5, 0xcb, 0x17, 0xaf, 0x33, 0xaa, 0xb5,
	0x06, 0xca, 0xd9, 0xc1, 0x67, 0xfd, 0xe1, 0xa6, 0xe1, 0x61, 0xd5, 0xd5, 0x7b, 0x9d, 0x51, 0x0c,
	0x6c, 0x15, 0x23, 0x04, 0x9d, 0x94, 0x2c, 0xa9, 0xd6, 0x1e, 0x28, 0x67, 0x5d, 0x2c, 0x63, 0x34,
	0x80, 0xbd, 0x05, 0xcd, 0x43, 0x1e, 0x67, 0x22, 0x66, 0xa9, 0xd6, 0x91, 0xd4, 0x3a, 0x84, 0x8e,
	0x60, 0x3b, 0xa3, 0x3c, 0x66, 0x0b, 0xed, 0xc1, 0x40, 0x39, 0xeb, 0xe1, 0x3a, 0x43, 0xcf, 0x60,
	0x9f, 0x84, 0x21, 0x2b, 0x52, 0xe1, 0x27, 0x71, 0x2e, 0xb4, 0xed, 0x41, 0xbb, 0x94, 0xd6, 0xd8,
	0x55, 0x9c, 0x8b, 0x52, 0xfa, 0xa2, 0x60, 0xbc, 0x58, 0x6a, 0x3b, 0x95, 0xb4, 0xca, 0x4a, 0x23,
	0x05, 0x4f, 0x72, 0x6d, 0x57, 0x4a, 0x64, 0x5c, 0x5e, 0x3c, 0x23, 0x3c, 0xa7, 0x3e, 0x2f, 0x12,
	0xaa, 0x75, 0xa5, 0x8f, 0xae, 0x44, 0x70, 0x91, 0x50, 0x74, 0x09, 0x07, 0x24, 0x8a, 0x38, 0x8d,
	0x88, 0xa8, 0x4b, 0x40, 0xde, 0xfd, 0x69, 0xf3, 0xee, 0x66, 0x5d, 0x15, 0xb3, 0xb4, 0x14, 0xe2,
	0xde, 0x4a, 0x26, 0xfb, 0x7c, 0x01, 0xdb, 0xb9, 0x20, 0xa2, 0xc8, 0xb5, 0x3d, 0xa9, 0x3f, 0x69,
	0xea, 0xeb, 0x59, 0xb8, 0xb2, 0x08, 0xd7, 0xc5, 0x48, 0x83, 0x9d, 0x90, 0x53, 0x22, 0x18, 0xd7,
	0xf6, 0xa5, 0xb5, 0xb7, 0x29, 0x3a, 0x84, 0x07, 0x29, 0x4b, 0x43, 0xaa, 0xf5, 0xe4, 0xac, 0xaa,
	0xe4, 0xf4, 0x77, 0x05, 0x7a, 0x6e, 0x11, 0x2c, 0x63, 0x31, 0x22, 0x82, 0xb8, 0x54, 0xfc, 0xd7,
	0x60, 0x57, 0x6d, 0x5a, 0x6b, 0x6d, 0xd0, 0x31, 0xec, 0x72, 0xf2, 0xd2, 0x5f, 0x10, 0x41, 0xea,
	0xa9, 0xed, 0x70, 0xf2, 0xb2, 0x6c, 0x89, 0xfa, 0xb0, 0x9b, 0x71, 0x76, 0x1b, 0x2f, 0x28, 0xaf,
	0xa7, 0xb6, 0xca, 0xd1, 0x13, 0xe8, 0xe6, 0x71, 0x94, 0x12, 0x51, 0x70, 0x2a, 0xa7, 0xd6, 0xc5,
	0xef, 0x80, 0xd3, 0x9f, 0x61, 0xe7, 0x7f, 0x99, 0x7a, 0x06, 0xfb, 0x41, 0xc2, 0xc2, 0x9f, 0xfc,
	0x1b, 0x1a, 0x47, 0x37, 0x42, 0x1a, 0xeb, 0xe0, 0x3d, 0x89, 0x7d, 0x2d, 0xa1, 0x0d, 0xdf, 0x9d,
	0x0d, 0xdf, 0xe7, 0xbf, 0x29, 0x00, 0xef, 0xfe, 0x27, 0x7a, 0x0c, 0x8f, 0xa6, 0xd8, 0xb4, 0xae,
	0x6c, 0xdf, 0xbb, 0x9e, 0xd9, 0xfe, 0x7c, 0xe2, 0xce, 0x6c, 0xcb, 0xb9, 0x74, 0xec, 0x91, 0xba,
	0x85, 0x4e, 0xe0, 0x78, 0x9d, 0x7c, 0xee, 0x4c, 0xfc, 0xb1, 0xe9, 0xfa, 0x33, 0xec, 0x58, 0xb6,
	0xaa, 0x20, 0x0d, 0x0e, 0xd7, 0x69, 0x6b, 0x8e, 0xb1, 0x3d, 0xb1, 0xae, 0xd5, 0x16, 0x7a, 0x08,
	0x1f, 0xaf, 0x33, 0xae, 0x37, 0xb5, 0xbe, 0x51, 0xdb, 0xe8, 0x08, 0xd0, 0x86, 0x00, 0x5f, 0xcf,
	0xbc, 0xa9, 0xda, 0x39, 0xff, 0x43, 0x81, 0xde, 0xc6, 0xdc, 0x91, 0x0e, 0x7d, 0x6c, 0x7f, 0x3b,
	0xb7, 0x5d, 0xcf, 0x77, 0x3d, 0xd3, 0x9b, 0xbb, 0x0d, 0x67, 0x7d, 0x38, 0x6a, 0xf0, 0x33, 0x7b,
	0x32, 0x72, 0x26, 0x63, 0x55, 0xf9, 0x00, 0xe7, 0xce, 0x2d, 0xcb, 0x76, 0x5d, 0xb5, 0x85, 0x8e,
	0xe1, 0x61, 0x83, 0xbb, 0x34, 0x9d, 0x2b, 0x7b, 0xa4, 0xb6, 0xd1, 0x23, 0xf8, 0xa4, 0x29, 0xf3,
	0xa6, 0x33, 0xb5, 0x73, 0xfe, 0x8b, 0x02, 0x1f, 0x35, 0x7e, 0x35, 0x1a, 0xc0, 0x13, 0x73, 0x3c,
	0xc6, 0xf6, 0xd8, 0xf4, 0x9c, 0xe9, 0xc4, 0xc7, 0xf3, 0xab, 0xe6, 0xdb, 0x69, 0x70, 0xf8, 0x5e,
	0x85, 0xf9, 0xdd, 0xb8, 0x7a, 0xb6, 0xf7, 0x98, 0xe7, 0xce, 0x44, 0x6d, 0x7d, 0x98, 0x31, 0xbf,
	0x57, 0xdb, 0x5f, 0x8d, 0xfe, 0xbc, 0xd3, 0x95, 0x37, 0x77, 0xba, 0xf2, 0xcf, 0x9d, 0xae, 0xfc,
	0x7a, 0xaf, 0x6f, 0xbd, 0xb9, 0xd7, 0xb7, 0xfe, 0xba, 0xd7, 0xb7, 0x7e, 0x38, 0x8f, 0x62, 0x71,
	0x53, 0x04, 0xc3, 0x90, 0x2d, 0x8d, 0xf1, 0xcc, 0x7b, 0xf5, 0x69, 0x94, 0xb0, 0x80, 0x24, 0x86,
	0x5c, 0xb0, 0xaf, 0xde, 0xae, 0xd8, 0x72, 0x5b, 0xe5, 0xc1, 0xb6, 0x5c, 0x7c, 0x9f, 0xff, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x7b, 0x96, 0x37, 0xa6, 0x7e, 0x05, 0x00, 0x00,
}

func (m *OracleRequestDoc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleRequestDoc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleRequestDoc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x68
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x62
	}
	if m.Status != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x58
	}
	if m.AggregateRule != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.AggregateRule))
		i--
		dAtA[i] = 0x50
	}
	if len(m.ParseRule) > 0 {
		i -= len(m.ParseRule)
		copy(dAtA[i:], m.ParseRule)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.ParseRule)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Urls) > 0 {
		for iNdEx := len(m.Urls) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Urls[iNdEx])
			copy(dAtA[i:], m.Urls[iNdEx])
			i = encodeVarintOracle(dAtA, i, uint64(len(m.Urls[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.Quorum != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.Quorum))
		i--
		dAtA[i] = 0x38
	}
	if len(m.AccountList) > 0 {
		for iNdEx := len(m.AccountList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AccountList[iNdEx])
			copy(dAtA[i:], m.AccountList[iNdEx])
			i = encodeVarintOracle(dAtA, i, uint64(len(m.AccountList[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Period != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.Period))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if m.OracleType != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.OracleType))
		i--
		dAtA[i] = 0x10
	}
	if m.RequestId != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SubmitDataSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitDataSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitDataSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RawData) > 0 {
		i -= len(m.RawData)
		copy(dAtA[i:], m.RawData)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.RawData)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Nonce != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x10
	}
	if m.RequestId != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DataSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RawData) > 0 {
		i -= len(m.RawData)
		copy(dAtA[i:], m.RawData)
		i = encodeVarintOracle(dAtA, i, uint64(len(m.RawData)))
		i--
		dAtA[i] = 0x22
	}
	if m.BlockHeight != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.Nonce != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x10
	}
	if m.RequestId != 0 {
		i = encodeVarintOracle(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintOracle(dAtA []byte, offset int, v uint64) int {
	offset -= sovOracle(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OracleRequestDoc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovOracle(uint64(m.RequestId))
	}
	if m.OracleType != 0 {
		n += 1 + sovOracle(uint64(m.OracleType))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	if m.Period != 0 {
		n += 1 + sovOracle(uint64(m.Period))
	}
	if len(m.AccountList) > 0 {
		for _, s := range m.AccountList {
			l = len(s)
			n += 1 + l + sovOracle(uint64(l))
		}
	}
	if m.Quorum != 0 {
		n += 1 + sovOracle(uint64(m.Quorum))
	}
	if len(m.Urls) > 0 {
		for _, s := range m.Urls {
			l = len(s)
			n += 1 + l + sovOracle(uint64(l))
		}
	}
	l = len(m.ParseRule)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	if m.AggregateRule != 0 {
		n += 1 + sovOracle(uint64(m.AggregateRule))
	}
	if m.Status != 0 {
		n += 1 + sovOracle(uint64(m.Status))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovOracle(uint64(m.Nonce))
	}
	return n
}

func (m *SubmitDataSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovOracle(uint64(m.RequestId))
	}
	if m.Nonce != 0 {
		n += 1 + sovOracle(uint64(m.Nonce))
	}
	l = len(m.RawData)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	return n
}

func (m *DataSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovOracle(uint64(m.RequestId))
	}
	if m.Nonce != 0 {
		n += 1 + sovOracle(uint64(m.Nonce))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovOracle(uint64(m.BlockHeight))
	}
	l = len(m.RawData)
	if l > 0 {
		n += 1 + l + sovOracle(uint64(l))
	}
	return n
}

func sovOracle(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOracle(x uint64) (n int) {
	return sovOracle(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OracleRequestDoc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleRequestDoc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleRequestDoc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleType", wireType)
			}
			m.OracleType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleType |= OracleType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			m.Period = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Period |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountList = append(m.AccountList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quorum", wireType)
			}
			m.Quorum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quorum |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Urls", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Urls = append(m.Urls, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParseRule", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParseRule = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregateRule", wireType)
			}
			m.AggregateRule = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AggregateRule |= AggregationRule(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= RequestStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitDataSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitDataSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitDataSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOracle(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOracle
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOracle
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOracle
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOracle
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOracle        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOracle          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOracle = fmt.Errorf("proto: unexpected end of group")
)
