// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: guru/oracle/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRegisterOracleRequestDoc represents a message to register a new oracle request document
type MsgRegisterOracleRequestDoc struct {
	ModeratorAddress string `protobuf:"bytes,1,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
	// The oracle request document to be registered
	RequestDoc OracleRequestDoc `protobuf:"bytes,2,opt,name=request_doc,json=requestDoc,proto3" json:"request_doc"`
}

func (m *MsgRegisterOracleRequestDoc) Reset()         { *m = MsgRegisterOracleRequestDoc{} }
func (m *MsgRegisterOracleRequestDoc) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterOracleRequestDoc) ProtoMessage()    {}
func (*MsgRegisterOracleRequestDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{0}
}
func (m *MsgRegisterOracleRequestDoc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterOracleRequestDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterOracleRequestDoc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterOracleRequestDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterOracleRequestDoc.Merge(m, src)
}
func (m *MsgRegisterOracleRequestDoc) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterOracleRequestDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterOracleRequestDoc.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterOracleRequestDoc proto.InternalMessageInfo

// MsgRegisterOracleRequestDocResponse defines the Msg/RegisterOracleRequestDoc response type
type MsgRegisterOracleRequestDocResponse struct {
	// ID of the registered oracle request
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *MsgRegisterOracleRequestDocResponse) Reset()         { *m = MsgRegisterOracleRequestDocResponse{} }
func (m *MsgRegisterOracleRequestDocResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterOracleRequestDocResponse) ProtoMessage()    {}
func (*MsgRegisterOracleRequestDocResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{1}
}
func (m *MsgRegisterOracleRequestDocResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterOracleRequestDocResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterOracleRequestDocResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterOracleRequestDocResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterOracleRequestDocResponse.Merge(m, src)
}
func (m *MsgRegisterOracleRequestDocResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterOracleRequestDocResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterOracleRequestDocResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterOracleRequestDocResponse proto.InternalMessageInfo

func (m *MsgRegisterOracleRequestDocResponse) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

// MsgUpdateOracleRequestDoc represents a message to update an existing oracle request document
type MsgUpdateOracleRequestDoc struct {
	ModeratorAddress string `protobuf:"bytes,1,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
	// The updated oracle request document
	RequestDoc OracleRequestDoc `protobuf:"bytes,2,opt,name=request_doc,json=requestDoc,proto3" json:"request_doc"`
	// Reason for the update
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgUpdateOracleRequestDoc) Reset()         { *m = MsgUpdateOracleRequestDoc{} }
func (m *MsgUpdateOracleRequestDoc) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateOracleRequestDoc) ProtoMessage()    {}
func (*MsgUpdateOracleRequestDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{2}
}
func (m *MsgUpdateOracleRequestDoc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateOracleRequestDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateOracleRequestDoc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateOracleRequestDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateOracleRequestDoc.Merge(m, src)
}
func (m *MsgUpdateOracleRequestDoc) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateOracleRequestDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateOracleRequestDoc.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateOracleRequestDoc proto.InternalMessageInfo

// MsgUpdateOracleRequestDocResponse defines the Msg/UpdateOracleRequestDoc response type
type MsgUpdateOracleRequestDocResponse struct {
	// ID of the updated oracle request
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *MsgUpdateOracleRequestDocResponse) Reset()         { *m = MsgUpdateOracleRequestDocResponse{} }
func (m *MsgUpdateOracleRequestDocResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateOracleRequestDocResponse) ProtoMessage()    {}
func (*MsgUpdateOracleRequestDocResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{3}
}
func (m *MsgUpdateOracleRequestDocResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateOracleRequestDocResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateOracleRequestDocResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateOracleRequestDocResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateOracleRequestDocResponse.Merge(m, src)
}
func (m *MsgUpdateOracleRequestDocResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateOracleRequestDocResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateOracleRequestDocResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateOracleRequestDocResponse proto.InternalMessageInfo

func (m *MsgUpdateOracleRequestDocResponse) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

// MsgSubmitOracleData represents a message to submit oracle data
type MsgSubmitOracleData struct {
	AuthorityAddress string `protobuf:"bytes,1,opt,name=authority_address,json=authorityAddress,proto3" json:"authority_address,omitempty"`
	// The oracle data set to be submitted, containing the raw data and metadata
	DataSet *SubmitDataSet `protobuf:"bytes,2,opt,name=data_set,json=dataSet,proto3" json:"data_set,omitempty"`
}

func (m *MsgSubmitOracleData) Reset()         { *m = MsgSubmitOracleData{} }
func (m *MsgSubmitOracleData) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitOracleData) ProtoMessage()    {}
func (*MsgSubmitOracleData) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{4}
}
func (m *MsgSubmitOracleData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitOracleData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitOracleData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitOracleData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitOracleData.Merge(m, src)
}
func (m *MsgSubmitOracleData) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitOracleData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitOracleData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitOracleData proto.InternalMessageInfo

// MsgSubmitOracleDataResponse defines the Msg/SubmitOracleData response type
type MsgSubmitOracleDataResponse struct {
}

func (m *MsgSubmitOracleDataResponse) Reset()         { *m = MsgSubmitOracleDataResponse{} }
func (m *MsgSubmitOracleDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitOracleDataResponse) ProtoMessage()    {}
func (*MsgSubmitOracleDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{5}
}
func (m *MsgSubmitOracleDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitOracleDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitOracleDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitOracleDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitOracleDataResponse.Merge(m, src)
}
func (m *MsgSubmitOracleDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitOracleDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitOracleDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitOracleDataResponse proto.InternalMessageInfo

// MsgUpdateModeratorAddress represents a message to update the moderator address
type MsgUpdateModeratorAddress struct {
	ModeratorAddress    string `protobuf:"bytes,1,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
	NewModeratorAddress string `protobuf:"bytes,2,opt,name=new_moderator_address,json=newModeratorAddress,proto3" json:"new_moderator_address,omitempty"`
}

func (m *MsgUpdateModeratorAddress) Reset()         { *m = MsgUpdateModeratorAddress{} }
func (m *MsgUpdateModeratorAddress) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateModeratorAddress) ProtoMessage()    {}
func (*MsgUpdateModeratorAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{6}
}
func (m *MsgUpdateModeratorAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateModeratorAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateModeratorAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateModeratorAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateModeratorAddress.Merge(m, src)
}
func (m *MsgUpdateModeratorAddress) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateModeratorAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateModeratorAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateModeratorAddress proto.InternalMessageInfo

// MsgUpdateModeratorAddressResponse defines the Msg/UpdateModeratorAddress response type
type MsgUpdateModeratorAddressResponse struct {
}

func (m *MsgUpdateModeratorAddressResponse) Reset()         { *m = MsgUpdateModeratorAddressResponse{} }
func (m *MsgUpdateModeratorAddressResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateModeratorAddressResponse) ProtoMessage()    {}
func (*MsgUpdateModeratorAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{7}
}
func (m *MsgUpdateModeratorAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateModeratorAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateModeratorAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateModeratorAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateModeratorAddressResponse.Merge(m, src)
}
func (m *MsgUpdateModeratorAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateModeratorAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateModeratorAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateModeratorAddressResponse proto.InternalMessageInfo

// MsgUpdatePredefinedOracle represents a message to update a predefined oracle
type MsgUpdatePredefinedOracle struct {
	ModeratorAddress string `protobuf:"bytes,1,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
	// The updated predefined oracle
	PredefinedOracle PredefinedOracle `protobuf:"bytes,2,opt,name=predefined_oracle,json=predefinedOracle,proto3" json:"predefined_oracle"`
}

func (m *MsgUpdatePredefinedOracle) Reset()         { *m = MsgUpdatePredefinedOracle{} }
func (m *MsgUpdatePredefinedOracle) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePredefinedOracle) ProtoMessage()    {}
func (*MsgUpdatePredefinedOracle) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{8}
}
func (m *MsgUpdatePredefinedOracle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePredefinedOracle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePredefinedOracle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePredefinedOracle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePredefinedOracle.Merge(m, src)
}
func (m *MsgUpdatePredefinedOracle) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePredefinedOracle) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePredefinedOracle.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePredefinedOracle proto.InternalMessageInfo

// MsgUpdatePredefinedOracleResponse defines the Msg/UpdatePredefinedOracle response type
type MsgUpdatePredefinedOracleResponse struct {
}

func (m *MsgUpdatePredefinedOracleResponse) Reset()         { *m = MsgUpdatePredefinedOracleResponse{} }
func (m *MsgUpdatePredefinedOracleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePredefinedOracleResponse) ProtoMessage()    {}
func (*MsgUpdatePredefinedOracleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{9}
}
func (m *MsgUpdatePredefinedOracleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePredefinedOracleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePredefinedOracleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePredefinedOracleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePredefinedOracleResponse.Merge(m, src)
}
func (m *MsgUpdatePredefinedOracleResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePredefinedOracleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePredefinedOracleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePredefinedOracleResponse proto.InternalMessageInfo

// MsgDeletePredefinedOracle represents a message to delete a predefined oracle
type MsgDeletePredefinedOracle struct {
	ModeratorAddress string `protobuf:"bytes,1,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
	// The predefined oracle type to be deleted
	Type PredefinedOracleType `protobuf:"varint,2,opt,name=type,proto3,enum=guru.oracle.v1.PredefinedOracleType" json:"type,omitempty"`
}

func (m *MsgDeletePredefinedOracle) Reset()         { *m = MsgDeletePredefinedOracle{} }
func (m *MsgDeletePredefinedOracle) String() string { return proto.CompactTextString(m) }
func (*MsgDeletePredefinedOracle) ProtoMessage()    {}
func (*MsgDeletePredefinedOracle) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{10}
}
func (m *MsgDeletePredefinedOracle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeletePredefinedOracle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeletePredefinedOracle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeletePredefinedOracle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeletePredefinedOracle.Merge(m, src)
}
func (m *MsgDeletePredefinedOracle) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeletePredefinedOracle) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeletePredefinedOracle.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeletePredefinedOracle proto.InternalMessageInfo

// MsgDeletePredefinedOracleResponse defines the Msg/DeletePredefinedOracle response type
type MsgDeletePredefinedOracleResponse struct {
}

func (m *MsgDeletePredefinedOracleResponse) Reset()         { *m = MsgDeletePredefinedOracleResponse{} }
func (m *MsgDeletePredefinedOracleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeletePredefinedOracleResponse) ProtoMessage()    {}
func (*MsgDeletePredefinedOracleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_febdd1f478235f42, []int{11}
}
func (m *MsgDeletePredefinedOracleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeletePredefinedOracleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeletePredefinedOracleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeletePredefinedOracleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeletePredefinedOracleResponse.Merge(m, src)
}
func (m *MsgDeletePredefinedOracleResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeletePredefinedOracleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeletePredefinedOracleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeletePredefinedOracleResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterOracleRequestDoc)(nil), "guru.oracle.v1.MsgRegisterOracleRequestDoc")
	proto.RegisterType((*MsgRegisterOracleRequestDocResponse)(nil), "guru.oracle.v1.MsgRegisterOracleRequestDocResponse")
	proto.RegisterType((*MsgUpdateOracleRequestDoc)(nil), "guru.oracle.v1.MsgUpdateOracleRequestDoc")
	proto.RegisterType((*MsgUpdateOracleRequestDocResponse)(nil), "guru.oracle.v1.MsgUpdateOracleRequestDocResponse")
	proto.RegisterType((*MsgSubmitOracleData)(nil), "guru.oracle.v1.MsgSubmitOracleData")
	proto.RegisterType((*MsgSubmitOracleDataResponse)(nil), "guru.oracle.v1.MsgSubmitOracleDataResponse")
	proto.RegisterType((*MsgUpdateModeratorAddress)(nil), "guru.oracle.v1.MsgUpdateModeratorAddress")
	proto.RegisterType((*MsgUpdateModeratorAddressResponse)(nil), "guru.oracle.v1.MsgUpdateModeratorAddressResponse")
	proto.RegisterType((*MsgUpdatePredefinedOracle)(nil), "guru.oracle.v1.MsgUpdatePredefinedOracle")
	proto.RegisterType((*MsgUpdatePredefinedOracleResponse)(nil), "guru.oracle.v1.MsgUpdatePredefinedOracleResponse")
	proto.RegisterType((*MsgDeletePredefinedOracle)(nil), "guru.oracle.v1.MsgDeletePredefinedOracle")
	proto.RegisterType((*MsgDeletePredefinedOracleResponse)(nil), "guru.oracle.v1.MsgDeletePredefinedOracleResponse")
}

func init() { proto.RegisterFile("guru/oracle/v1/tx.proto", fileDescriptor_febdd1f478235f42) }

var fileDescriptor_febdd1f478235f42 = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x4f, 0xd4, 0x4e,
	0x18, 0xde, 0x02, 0x3f, 0x7e, 0x32, 0x24, 0x04, 0x16, 0x84, 0x65, 0x09, 0x05, 0x17, 0x0f, 0x08,
	0x61, 0x9b, 0x85, 0x0b, 0xf1, 0xe6, 0x66, 0x0d, 0x31, 0x71, 0x23, 0xe9, 0xe2, 0xc5, 0x4b, 0x33,
	0xdb, 0x19, 0x87, 0x26, 0xdb, 0x4e, 0x9d, 0x99, 0xf2, 0x27, 0xf1, 0xe4, 0xc9, 0xa3, 0x1f, 0x81,
	0x8f, 0xe0, 0xc1, 0x78, 0xf2, 0x03, 0xe0, 0xc1, 0x84, 0x78, 0xd1, 0x93, 0x31, 0xec, 0x41, 0x3f,
	0x86, 0x69, 0xa7, 0x5b, 0x71, 0xda, 0xee, 0x2e, 0x09, 0x26, 0xde, 0xda, 0xf7, 0xdf, 0xf3, 0x3e,
	0xcf, 0xbc, 0xf3, 0x66, 0xc0, 0x02, 0x09, 0x58, 0x60, 0x50, 0x06, 0xed, 0x0e, 0x36, 0x8e, 0x6a,
	0x86, 0x38, 0xa9, 0xfa, 0x8c, 0x0a, 0x5a, 0x9c, 0x0a, 0x1d, 0x55, 0xe9, 0xa8, 0x1e, 0xd5, 0xca,
	0x0b, 0x36, 0xe5, 0x2e, 0xe5, 0x86, 0xcb, 0x49, 0x18, 0xe7, 0x72, 0x22, 0x03, 0xcb, 0x8b, 0xd2,
	0x61, 0x45, 0x7f, 0x86, 0xfc, 0x89, 0x5d, 0x73, 0x84, 0x12, 0x2a, 0xed, 0xe1, 0x57, 0x6c, 0x5d,
	0x52, 0x20, 0x63, 0x0c, 0xe9, 0xd4, 0x63, 0x98, 0x36, 0xe4, 0xa1, 0xb3, 0x8d, 0x05, 0xac, 0x19,
	0x36, 0x75, 0x3c, 0xe9, 0xaf, 0x7c, 0xd2, 0xc0, 0x52, 0x93, 0x13, 0x13, 0x13, 0x87, 0x0b, 0xcc,
	0x9e, 0x44, 0xb9, 0x26, 0x7e, 0x11, 0x60, 0x2e, 0x1a, 0xd4, 0x2e, 0x3e, 0x04, 0x33, 0x2e, 0x45,
	0x98, 0x41, 0x41, 0x99, 0x05, 0x11, 0x62, 0x98, 0xf3, 0x92, 0xb6, 0xaa, 0xad, 0x4f, 0xd4, 0x4b,
	0x9f, 0xdf, 0x6d, 0xcd, 0xc5, 0xfd, 0x3d, 0x90, 0x9e, 0x96, 0x60, 0x8e, 0x47, 0xcc, 0xe9, 0x24,
	0x25, 0xb6, 0x17, 0xf7, 0xc0, 0x24, 0x93, 0x45, 0x2d, 0x44, 0xed, 0xd2, 0xc8, 0xaa, 0xb6, 0x3e,
	0xb9, 0xbd, 0x5a, 0xfd, 0x53, 0x93, 0xaa, 0x8a, 0x5e, 0x1f, 0x3b, 0xff, 0xb6, 0x52, 0x30, 0x01,
	0x4b, 0x2c, 0xf7, 0xf5, 0xd7, 0x67, 0x2b, 0x85, 0x9f, 0x67, 0x2b, 0x85, 0x57, 0x3f, 0xde, 0x6e,
	0xa4, 0x5b, 0xab, 0x34, 0xc0, 0x5a, 0x1f, 0x3a, 0x26, 0xe6, 0x3e, 0xf5, 0x38, 0x2e, 0x2e, 0x83,
	0x5e, 0x51, 0xcb, 0x41, 0x11, 0x9f, 0x31, 0x73, 0x22, 0xb6, 0x3c, 0x42, 0x95, 0xae, 0x06, 0x16,
	0x9b, 0x9c, 0x3c, 0xf5, 0x11, 0x14, 0xf8, 0x5f, 0xd7, 0xa4, 0x38, 0x0f, 0xc6, 0x19, 0x86, 0x9c,
	0x7a, 0xa5, 0xd1, 0xb0, 0x09, 0x33, 0xfe, 0x1b, 0xa8, 0x55, 0x1d, 0xdc, 0xc9, 0x25, 0x39, 0xac,
	0x52, 0xef, 0x35, 0x30, 0xdb, 0xe4, 0xa4, 0x15, 0xb4, 0x5d, 0x47, 0xc8, 0x22, 0x0d, 0x28, 0x60,
	0xa8, 0x11, 0x0c, 0xc4, 0x21, 0x65, 0x8e, 0x38, 0x1d, 0x5e, 0xa3, 0x24, 0xa5, 0xa7, 0xd1, 0x2e,
	0xb8, 0x85, 0xa0, 0x80, 0x16, 0xc7, 0x22, 0x16, 0x68, 0x59, 0x15, 0x48, 0x42, 0x87, 0xa0, 0x2d,
	0x2c, 0xcc, 0xff, 0x91, 0xfc, 0x50, 0xc8, 0xa7, 0x7a, 0xa9, 0x2c, 0x47, 0x73, 0xaf, 0xf6, 0xdd,
	0xa3, 0x5d, 0xb9, 0xb8, 0x3a, 0x01, 0x4d, 0xf5, 0xe8, 0x6e, 0x68, 0x02, 0x1e, 0x83, 0xdb, 0x1e,
	0x3e, 0xb6, 0xd2, 0xa5, 0x46, 0x06, 0x94, 0x9a, 0xf5, 0xf0, 0xb1, 0xda, 0xd4, 0xc0, 0xe3, 0x5e,
	0xbb, 0x72, 0xdc, 0x6a, 0x72, 0xc2, 0xfb, 0xcb, 0x55, 0xde, 0xfb, 0x0c, 0x23, 0xfc, 0xdc, 0xf1,
	0x30, 0x92, 0x0a, 0xdd, 0x14, 0xef, 0x16, 0x98, 0xf1, 0x93, 0xd2, 0x96, 0x3c, 0xca, 0xbc, 0xf9,
	0x57, 0x7b, 0x88, 0xe7, 0x7f, 0xda, 0x57, 0xec, 0xd7, 0xa2, 0xaf, 0x16, 0x4d, 0xe8, 0x7f, 0x90,
	0xf4, 0x1b, 0xb8, 0x83, 0xff, 0x1e, 0xfd, 0x5d, 0x30, 0x26, 0x4e, 0x7d, 0xc9, 0x78, 0x6a, 0xfb,
	0xee, 0x20, 0xc6, 0x07, 0xa7, 0x3e, 0x36, 0xa3, 0x8c, 0x21, 0x39, 0x66, 0x77, 0xdf, 0xe3, 0xb8,
	0xfd, 0xf1, 0x3f, 0x30, 0xda, 0xe4, 0xa4, 0xf8, 0x12, 0x94, 0x72, 0xd7, 0xfe, 0xa6, 0xda, 0x54,
	0x9f, 0xa5, 0x5a, 0xde, 0xb9, 0x46, 0x70, 0xb2, 0x57, 0x8e, 0xc0, 0x7c, 0xce, 0x7a, 0xbd, 0x97,
	0x51, 0x2e, 0x3b, 0xb4, 0x5c, 0x1b, 0x3a, 0x34, 0xc1, 0x45, 0x60, 0x3a, 0xb5, 0xac, 0xd6, 0x32,
	0xca, 0xa8, 0x41, 0xe5, 0xcd, 0x21, 0x82, 0xd2, 0xec, 0x52, 0xab, 0x23, 0x9f, 0x9d, 0x1a, 0xda,
	0x87, 0x5d, 0xde, 0xf5, 0xfd, 0x8d, 0x9b, 0x9a, 0xdd, 0x7c, 0x5c, 0x35, 0xb4, 0x0f, 0x6e, 0xde,
	0x4c, 0x85, 0xb8, 0x39, 0x77, 0x26, 0x0b, 0x37, 0x3b, 0x34, 0x13, 0xb7, 0xff, 0x2c, 0xd7, 0x1b,
	0xe7, 0x97, 0xba, 0x76, 0x71, 0xa9, 0x6b, 0xdf, 0x2f, 0x75, 0xed, 0x4d, 0x57, 0x2f, 0x5c, 0x74,
	0xf5, 0xc2, 0xd7, 0xae, 0x5e, 0x78, 0xb6, 0x41, 0x1c, 0x71, 0x18, 0xb4, 0xab, 0x36, 0x75, 0x8d,
	0xbd, 0xfd, 0x83, 0x93, 0x2d, 0xd2, 0xa1, 0x6d, 0xd8, 0x31, 0xa2, 0xc7, 0xd2, 0x49, 0xef, 0xb9,
	0x14, 0xde, 0x2a, 0xde, 0x1e, 0x8f, 0xde, 0x42, 0x3b, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x66,
	0x24, 0xe1, 0xf6, 0xbd, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterOracleRequestDoc defines a method for registering a new oracle request document
	RegisterOracleRequestDoc(ctx context.Context, in *MsgRegisterOracleRequestDoc, opts ...grpc.CallOption) (*MsgRegisterOracleRequestDocResponse, error)
	// UpdateOracleRequestDoc defines a method for updating an existing oracle request document
	UpdateOracleRequestDoc(ctx context.Context, in *MsgUpdateOracleRequestDoc, opts ...grpc.CallOption) (*MsgUpdateOracleRequestDocResponse, error)
	// SubmitOracleData defines a method for submitting oracle data
	SubmitOracleData(ctx context.Context, in *MsgSubmitOracleData, opts ...grpc.CallOption) (*MsgSubmitOracleDataResponse, error)
	// UpdateModeratorAddress defines a method for updating the moderator address
	UpdateModeratorAddress(ctx context.Context, in *MsgUpdateModeratorAddress, opts ...grpc.CallOption) (*MsgUpdateModeratorAddressResponse, error)
	// UpdatePredefinedOracle defines a method for updating a predefined oracle
	UpdatePredefinedOracle(ctx context.Context, in *MsgUpdatePredefinedOracle, opts ...grpc.CallOption) (*MsgUpdatePredefinedOracleResponse, error)
	// DeletePredefinedOracle defines a method for deleting a predefined oracle
	DeletePredefinedOracle(ctx context.Context, in *MsgDeletePredefinedOracle, opts ...grpc.CallOption) (*MsgDeletePredefinedOracleResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterOracleRequestDoc(ctx context.Context, in *MsgRegisterOracleRequestDoc, opts ...grpc.CallOption) (*MsgRegisterOracleRequestDocResponse, error) {
	out := new(MsgRegisterOracleRequestDocResponse)
	err := c.cc.Invoke(ctx, "/guru.oracle.v1.Msg/RegisterOracleRequestDoc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateOracleRequestDoc(ctx context.Context, in *MsgUpdateOracleRequestDoc, opts ...grpc.CallOption) (*MsgUpdateOracleRequestDocResponse, error) {
	out := new(MsgUpdateOracleRequestDocResponse)
	err := c.cc.Invoke(ctx, "/guru.oracle.v1.Msg/UpdateOracleRequestDoc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitOracleData(ctx context.Context, in *MsgSubmitOracleData, opts ...grpc.CallOption) (*MsgSubmitOracleDataResponse, error) {
	out := new(MsgSubmitOracleDataResponse)
	err := c.cc.Invoke(ctx, "/guru.oracle.v1.Msg/SubmitOracleData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateModeratorAddress(ctx context.Context, in *MsgUpdateModeratorAddress, opts ...grpc.CallOption) (*MsgUpdateModeratorAddressResponse, error) {
	out := new(MsgUpdateModeratorAddressResponse)
	err := c.cc.Invoke(ctx, "/guru.oracle.v1.Msg/UpdateModeratorAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdatePredefinedOracle(ctx context.Context, in *MsgUpdatePredefinedOracle, opts ...grpc.CallOption) (*MsgUpdatePredefinedOracleResponse, error) {
	out := new(MsgUpdatePredefinedOracleResponse)
	err := c.cc.Invoke(ctx, "/guru.oracle.v1.Msg/UpdatePredefinedOracle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeletePredefinedOracle(ctx context.Context, in *MsgDeletePredefinedOracle, opts ...grpc.CallOption) (*MsgDeletePredefinedOracleResponse, error) {
	out := new(MsgDeletePredefinedOracleResponse)
	err := c.cc.Invoke(ctx, "/guru.oracle.v1.Msg/DeletePredefinedOracle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterOracleRequestDoc defines a method for registering a new oracle request document
	RegisterOracleRequestDoc(context.Context, *MsgRegisterOracleRequestDoc) (*MsgRegisterOracleRequestDocResponse, error)
	// UpdateOracleRequestDoc defines a method for updating an existing oracle request document
	UpdateOracleRequestDoc(context.Context, *MsgUpdateOracleRequestDoc) (*MsgUpdateOracleRequestDocResponse, error)
	// SubmitOracleData defines a method for submitting oracle data
	SubmitOracleData(context.Context, *MsgSubmitOracleData) (*MsgSubmitOracleDataResponse, error)
	// UpdateModeratorAddress defines a method for updating the moderator address
	UpdateModeratorAddress(context.Context, *MsgUpdateModeratorAddress) (*MsgUpdateModeratorAddressResponse, error)
	// UpdatePredefinedOracle defines a method for updating a predefined oracle
	UpdatePredefinedOracle(context.Context, *MsgUpdatePredefinedOracle) (*MsgUpdatePredefinedOracleResponse, error)
	// DeletePredefinedOracle defines a method for deleting a predefined oracle
	DeletePredefinedOracle(context.Context, *MsgDeletePredefinedOracle) (*MsgDeletePredefinedOracleResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterOracleRequestDoc(ctx context.Context, req *MsgRegisterOracleRequestDoc) (*MsgRegisterOracleRequestDocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterOracleRequestDoc not implemented")
}
func (*UnimplementedMsgServer) UpdateOracleRequestDoc(ctx context.Context, req *MsgUpdateOracleRequestDoc) (*MsgUpdateOracleRequestDocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOracleRequestDoc not implemented")
}
func (*UnimplementedMsgServer) SubmitOracleData(ctx context.Context, req *MsgSubmitOracleData) (*MsgSubmitOracleDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOracleData not implemented")
}
func (*UnimplementedMsgServer) UpdateModeratorAddress(ctx context.Context, req *MsgUpdateModeratorAddress) (*MsgUpdateModeratorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModeratorAddress not implemented")
}
func (*UnimplementedMsgServer) UpdatePredefinedOracle(ctx context.Context, req *MsgUpdatePredefinedOracle) (*MsgUpdatePredefinedOracleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePredefinedOracle not implemented")
}
func (*UnimplementedMsgServer) DeletePredefinedOracle(ctx context.Context, req *MsgDeletePredefinedOracle) (*MsgDeletePredefinedOracleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePredefinedOracle not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterOracleRequestDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterOracleRequestDoc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterOracleRequestDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.oracle.v1.Msg/RegisterOracleRequestDoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterOracleRequestDoc(ctx, req.(*MsgRegisterOracleRequestDoc))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateOracleRequestDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateOracleRequestDoc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateOracleRequestDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.oracle.v1.Msg/UpdateOracleRequestDoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateOracleRequestDoc(ctx, req.(*MsgUpdateOracleRequestDoc))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitOracleData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitOracleData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitOracleData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.oracle.v1.Msg/SubmitOracleData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitOracleData(ctx, req.(*MsgSubmitOracleData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateModeratorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateModeratorAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateModeratorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.oracle.v1.Msg/UpdateModeratorAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateModeratorAddress(ctx, req.(*MsgUpdateModeratorAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdatePredefinedOracle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePredefinedOracle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePredefinedOracle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.oracle.v1.Msg/UpdatePredefinedOracle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePredefinedOracle(ctx, req.(*MsgUpdatePredefinedOracle))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeletePredefinedOracle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeletePredefinedOracle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeletePredefinedOracle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.oracle.v1.Msg/DeletePredefinedOracle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeletePredefinedOracle(ctx, req.(*MsgDeletePredefinedOracle))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guru.oracle.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterOracleRequestDoc",
			Handler:    _Msg_RegisterOracleRequestDoc_Handler,
		},
		{
			MethodName: "UpdateOracleRequestDoc",
			Handler:    _Msg_UpdateOracleRequestDoc_Handler,
		},
		{
			MethodName: "SubmitOracleData",
			Handler:    _Msg_SubmitOracleData_Handler,
		},
		{
			MethodName: "UpdateModeratorAddress",
			Handler:    _Msg_UpdateModeratorAddress_Handler,
		},
		{
			MethodName: "UpdatePredefinedOracle",
			Handler:    _Msg_UpdatePredefinedOracle_Handler,
		},
		{
			MethodName: "DeletePredefinedOracle",
			Handler:    _Msg_DeletePredefinedOracle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guru/oracle/v1/tx.proto",
}

func (m *MsgRegisterOracleRequestDoc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterOracleRequestDoc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterOracleRequestDoc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RequestDoc.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterOracleRequestDocResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterOracleRequestDocResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterOracleRequestDocResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateOracleRequestDoc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateOracleRequestDoc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateOracleRequestDoc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.RequestDoc.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateOracleRequestDocResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateOracleRequestDocResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateOracleRequestDocResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitOracleData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitOracleData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitOracleData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DataSet != nil {
		{
			size, err := m.DataSet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuthorityAddress) > 0 {
		i -= len(m.AuthorityAddress)
		copy(dAtA[i:], m.AuthorityAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AuthorityAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitOracleDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitOracleDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitOracleDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateModeratorAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateModeratorAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateModeratorAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewModeratorAddress) > 0 {
		i -= len(m.NewModeratorAddress)
		copy(dAtA[i:], m.NewModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewModeratorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateModeratorAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateModeratorAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateModeratorAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePredefinedOracle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePredefinedOracle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePredefinedOracle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PredefinedOracle.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePredefinedOracleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePredefinedOracleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePredefinedOracleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeletePredefinedOracle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeletePredefinedOracle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeletePredefinedOracle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeletePredefinedOracleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeletePredefinedOracleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeletePredefinedOracleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterOracleRequestDoc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.RequestDoc.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRegisterOracleRequestDocResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovTx(uint64(m.RequestId))
	}
	return n
}

func (m *MsgUpdateOracleRequestDoc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.RequestDoc.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateOracleRequestDocResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovTx(uint64(m.RequestId))
	}
	return n
}

func (m *MsgSubmitOracleData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuthorityAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DataSet != nil {
		l = m.DataSet.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitOracleDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateModeratorAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateModeratorAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdatePredefinedOracle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.PredefinedOracle.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdatePredefinedOracleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeletePredefinedOracle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovTx(uint64(m.Type))
	}
	return n
}

func (m *MsgDeletePredefinedOracleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterOracleRequestDoc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterOracleRequestDoc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterOracleRequestDoc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestDoc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RequestDoc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterOracleRequestDocResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterOracleRequestDocResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterOracleRequestDocResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateOracleRequestDoc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateOracleRequestDoc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateOracleRequestDoc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestDoc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RequestDoc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateOracleRequestDocResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateOracleRequestDocResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateOracleRequestDocResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitOracleData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitOracleData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitOracleData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorityAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DataSet == nil {
				m.DataSet = &SubmitDataSet{}
			}
			if err := m.DataSet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitOracleDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitOracleDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitOracleDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateModeratorAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateModeratorAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateModeratorAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateModeratorAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateModeratorAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateModeratorAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePredefinedOracle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePredefinedOracle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePredefinedOracle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PredefinedOracle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PredefinedOracle.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePredefinedOracleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePredefinedOracleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePredefinedOracleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeletePredefinedOracle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeletePredefinedOracle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeletePredefinedOracle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= PredefinedOracleType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeletePredefinedOracleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeletePredefinedOracleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeletePredefinedOracleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
